import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useTelemetryStore } from '../store/telemetry';
import { formatDuration, formatDataThroughput } from '../utils/formatting';
import { Activity, Zap, Radio } from 'lucide-react';
export function ExperimentHeader() {
    const readings = useTelemetryStore((s) => s.readings);
    const messageCount = useTelemetryStore((s) => s.messageCount);
    const runtime = readings.length > 0 ? readings[readings.length - 1].systemUptime : 0;
    const signalIntegrity = readings.length > 0 ? readings[readings.length - 1].signalIntegrity : 100;
    const throughput = formatDataThroughput(messageCount, runtime);
    return (_jsx("div", { className: "border-b border-lab-800 bg-lab-900 px-6 py-4", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-6", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "w-10 h-10 rounded-lg bg-gradient-accent flex items-center justify-center shadow-glow", children: _jsx(Zap, { className: "text-lab-950", size: 20, strokeWidth: 3 }) }), _jsxs("div", { children: [_jsx("h1", { className: "text-xl font-bold text-white", children: "EXP-2026-0219" }), _jsx("p", { className: "text-xs text-slate-400 font-medium", children: "Real-time telemetry" })] })] }), _jsxs("div", { className: "flex gap-8 ml-4", children: [_jsxs("div", { className: "flex items-center gap-3 px-4 py-2 rounded-lg bg-lab-800 border border-lab-700", children: [_jsx(Activity, { size: 16, className: "text-slate-400" }), _jsxs("div", { children: [_jsx("p", { className: "text-xs text-slate-400 uppercase tracking-wide font-semibold", children: "Runtime" }), _jsx("p", { className: "font-mono text-sm text-white font-semibold", children: formatDuration(runtime) })] })] }), _jsxs("div", { className: "flex items-center gap-3 px-4 py-2 rounded-lg bg-lab-800 border border-lab-700", children: [_jsx(Radio, { size: 16, className: "text-slate-400" }), _jsxs("div", { children: [_jsx("p", { className: "text-xs text-slate-400 uppercase tracking-wide font-semibold", children: "Throughput" }), _jsx("p", { className: "font-mono text-sm text-white font-semibold", children: throughput })] })] }), _jsxs("div", { className: "flex items-center gap-3 px-4 py-2 rounded-lg bg-lab-800 border border-lab-700", children: [_jsx("div", { className: "w-6 h-6 rounded-full bg-lab-700 flex items-center justify-center", children: _jsx("div", { className: "w-4 h-4 rounded-full bg-gradient-accent" }) }), _jsxs("div", { children: [_jsx("p", { className: "text-xs text-slate-400 uppercase tracking-wide font-semibold", children: "Integrity" }), _jsxs("p", { className: "font-mono text-sm text-white font-semibold", children: [signalIntegrity.toFixed(1), "%"] })] })] })] })] }), _jsxs("div", { className: "flex items-center gap-2 px-4 py-2 rounded-lg bg-lab-800 border border-lab-700", children: [_jsx("div", { className: "w-2 h-2 rounded-full bg-emerald-500 animate-pulse-subtle" }), _jsx("span", { className: "text-sm font-medium text-slate-300", children: "Streaming" })] })] }) }));
}
