import { jsx as _jsx, Fragment as _Fragment, jsxs as _jsxs } from "react/jsx-runtime";
import { useTelemetryStore } from '../store/telemetry';
import { PauseIcon, PlayIcon, ChevronDownIcon, SettingsIcon, ZapOffIcon, RotateCwIcon } from 'lucide-react';
export function Sidebar() {
    const isPaused = useTelemetryStore((s) => s.isPaused);
    const setIsPaused = useTelemetryStore((s) => s.setIsPaused);
    const anomalySensitivity = useTelemetryStore((s) => s.anomalySensitivity);
    const setAnomalySensitivity = useTelemetryStore((s) => s.setAnomalySensitivity);
    const calibrationMode = useTelemetryStore((s) => s.calibrationMode);
    const setCalibrationMode = useTelemetryStore((s) => s.setCalibrationMode);
    const signalNormalization = useTelemetryStore((s) => s.signalNormalizationActive);
    const setSignalNormalization = useTelemetryStore((s) => s.setSignalNormalization);
    const connected = useTelemetryStore((s) => s.connected);
    return (_jsxs("div", { className: "card flex flex-col overflow-y-auto h-full", children: [_jsx("div", { className: "p-4 border-b border-lab-800", children: _jsx("button", { onClick: () => setIsPaused(!isPaused), className: "w-full btn-primary text-sm", children: isPaused ? (_jsxs(_Fragment, { children: [_jsx(PlayIcon, { size: 16 }), "Resume"] })) : (_jsxs(_Fragment, { children: [_jsx(PauseIcon, { size: 16 }), "Pause"] })) }) }), _jsxs("div", { className: "p-4 border-b border-lab-800", children: [_jsx("label", { className: "text-xs font-semibold text-slate-400 uppercase tracking-wide", children: "Active experiment" }), _jsxs("div", { className: "mt-2 flex items-center justify-between px-3 py-2.5 bg-lab-800 hover:bg-lab-700 rounded-lg text-sm text-slate-100 cursor-pointer transition-all duration-200 border border-lab-700 hover:border-lab-600", children: [_jsx("span", { className: "font-semibold", children: "EXP-2026-0219" }), _jsx(ChevronDownIcon, { size: 16 })] })] }), _jsxs("div", { className: "p-4 border-b border-lab-800", children: [_jsx("label", { className: "text-xs font-semibold text-slate-400 uppercase tracking-wide", children: "Connection" }), _jsxs("div", { className: "mt-3 flex items-center gap-3 px-3 py-2.5 rounded-lg bg-lab-800 border border-lab-700", children: [_jsx("div", { className: `w-2.5 h-2.5 rounded-full ${connected ? 'bg-gradient-accent animate-pulse-subtle' : 'bg-slate-600'}` }), _jsxs("div", { children: [_jsx("p", { className: "text-xs font-semibold text-slate-300", children: connected ? 'Connected' : 'Offline' }), _jsx("p", { className: "text-xs text-slate-500", children: connected ? 'Data streaming' : 'Waiting...' })] })] })] }), _jsxs("div", { className: "p-4 border-b border-lab-800", children: [_jsxs("div", { className: "flex items-center justify-between mb-3", children: [_jsx("label", { className: "text-xs font-semibold text-slate-400 uppercase tracking-wide", children: "Sensitivity" }), _jsxs("span", { className: "text-xs font-mono bg-lab-800 text-cyan-400 px-2 py-1 rounded", children: [anomalySensitivity.toFixed(1), "\u03C3"] })] }), _jsx("input", { type: "range", min: "1.5", max: "3.0", step: "0.1", value: anomalySensitivity, onChange: (e) => setAnomalySensitivity(parseFloat(e.target.value)), className: "w-full" }), _jsx("p", { className: "text-xs text-slate-500 mt-2", children: "Adjusts detection threshold" })] }), _jsxs("div", { className: "p-4 border-b border-lab-800", children: [_jsx("label", { className: "text-xs font-semibold text-slate-400 uppercase tracking-wide mb-3 block", children: "Modes" }), _jsxs("div", { className: "space-y-2", children: [_jsxs("button", { onClick: () => setCalibrationMode(!calibrationMode), className: `w-full flex items-center gap-2 px-3 py-2.5 rounded-lg text-sm font-medium transition-all duration-200 border ${calibrationMode
                                    ? 'bg-lab-700 border-lab-600 text-white shadow-glow'
                                    : 'bg-lab-800 border-lab-700 text-slate-300 hover:bg-lab-700'}`, children: [_jsx(RotateCwIcon, { size: 14 }), "Calibration"] }), _jsxs("button", { onClick: () => setSignalNormalization(!signalNormalization), className: `w-full flex items-center gap-2 px-3 py-2.5 rounded-lg text-sm font-medium transition-all duration-200 border ${signalNormalization
                                    ? 'bg-lab-700 border-lab-600 text-white shadow-glow'
                                    : 'bg-lab-800 border-lab-700 text-slate-300 hover:bg-lab-700'}`, children: [_jsx(ZapOffIcon, { size: 14 }), "Normalization"] })] })] }), _jsx("div", { className: "p-4 border-b border-lab-800", children: _jsxs("button", { className: "w-full btn-secondary text-sm", children: [_jsx(SettingsIcon, { size: 16 }), "Settings"] }) }), _jsx("div", { className: "p-4 mt-auto", children: _jsxs("div", { className: "bg-lab-800 rounded-lg p-3 border border-lab-700", children: [_jsx("p", { className: "text-xs font-semibold text-slate-300 mb-2", children: "Tip" }), _jsx("p", { className: "text-xs text-slate-400 leading-relaxed", children: "Adjust sensitivity to tune detection. Higher values = fewer alerts." })] }) })] }));
}
